# ./EKS/Service.yaml

apiVersion: v1
kind: Service
metadata:
  name: bespin-eks-svc
spec:
  ports:
    - name: "80"
      port: 80
      targetPort: 80
  selector:
    app: bespin-eks
  type: LoadBalancer